### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by xinjian555** [jhoopmann/eric-php-extension#1]
How to use?

**Comment by jhoopmann** [comment]
You have to compile as php extension - phpize && ./configure && make [ && make install ], activate extension in ini and use the few described working functions in php_eric.c. Your given GOV certificate path has to be written fixed in php_eric.c, so you have to be registered as developer at german tax and revenue office and download the ERiC C library libericapi.so/dll. You can extend it for your own requirements. It's just an example on how the GOV communication could be done directly via PHP C extension instead of pushing the tax data to external services which would then handle the communication with the GOV. 

in PHP you would write code like 
eric_init
fetch tax office via eric_get_tax_office_country_numbers and eric_get_tax_offices_for_country_number
eric_transfer with clients tax number formatted via eric_format_tax_number and country_code + tax_office_id 
pass the correct XML. For XML you can take a look in the ELSTER documentation. 
eric_close

Currently registered working functions are 
    PHP_FE(eric_init, NULL)
    PHP_FE(eric_close, NULL)
    PHP_FE(eric_get_tax_office_country_numbers, NULL)
    PHP_FE(eric_get_tax_offices_for_country_number, arginfo_eric_get_tax_offices_for_country_number)
    PHP_FE(eric_format_tax_number, arginfo_eric_format_tax_number)
    PHP_FE(eric_format_tax_number_to_elster, arginfo_eric_format_tax_number_to_elster)
    PHP_FE(eric_transfer, arginfo_eric_transfer)
    PHP_FE(eric_get_error, NULL)
    PHP_FE(eric_get_error_code, NULL)
that's enough to send the XML tax report to GOV tax office

But like i described in readme, there are still multiproc issues. Currently you cannot call transfer for multiple requests in same time cause of memory violations in accessing error states and certificate handles for example. Extend the error states and handles to globals and use request based array mappings.
